# Generated by Django 4.1 on 2023-03-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duracion', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('numero_suscripciones', models.PositiveIntegerField(default=0)),
                ('plan_popular', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['precio'],
            },
        ),
    ]
